using SpotifyStalker.Interface;
using Bogus;
using System.Collections.Generic;

namespace SpotifyStalker.Service
{
    public class RandomProvider : IRandomProvider
    {
        public string GetPersonName() => new Faker().Person.FirstName;

        public string GetWord() => new Randomizer().Word().ToString();

        public T PickRandom<T>(IEnumerable<T> items) => new Faker().PickRandom(items);

        public string GetLocation() => new Faker().Address.Country().ToString();

        public string GetGenre()
        {
            var genres = new List<string>() {
                "2 Tone",
                "2-step garage",
                "4-beat",
                "Acid breaks",
                "Acid house",
                "Acid jazz",
                "Acid rock",
                "Acid techno",
                "Acid trance",
                "Acousmatic",
                "Adult alternative",
                "Adult contemporary",
                "African",
                "African blues",
                "African electronic dance",
                "African heavy metal",
                "African hip hop",
                "Afro house",
                "Afro pop",
                "Afro/cosmic",
                "Afrobeat",
                "Afrobeats",
                "Afro-Cuban jazz",
                "Afroswing",
                "Aggrotech",
                "Alternative country",
                "Alternative dance",
                "Alternative hip hop",
                "Alternative metal",
                "Alternative rock",
                "Alt-jazz",
                "Amapiano",
                "Ambient",
                "Ambient dub",
                "Ambient house",
                "Ambient techno",
                "American folk revival",
                "Americana",
                "Anarcho punk",
                "Andean new-age",
                "Anti-folk",
                "Apala",
                "Arab pop",
                "Arabesque",
                "Arabic pop",
                "ars antiqua",
                "ars nova",
                "ars subtilior",
                "Art punk",
                "Art rock",
                "Asian",
                "Asian underground",
                "Atmospheric Black Metal",
                "Australian country",
                "Australian hip hop",
                "Austropop",
                "Avant-garde",
                "Avant-garde jazz",
                "Avant-garde metal",
                "Axé",
                "Azonto",
                "Bachata",
                "Background",
                "Baggy",
                "Baila",
                "Baithak Gana",
                "Bakersfield sound",
                "Balearic beat",
                "Balearic trance",
                "Baltimore club",
                "Banda",
                "Baroque",
                "Baroque pop",
                "Bass",
                "Bass house",
                "Bassline",
                "Baul",
                "Beat",
                "Beautiful",
                "Bebop",
                "Benga",
                "Berlin School",
                "Bhangra",
                "Big beat",
                "Big room house",
                "Bikutsi",
                "Birmingham sound",
                "Bitpop",
                "Black metal",
                "Blackened death metal",
                "Blackgaze",
                "Bleep techno",
                "Blue-eyed soul",
                "Bluegrass",
                "Blues",
                "Blues rock",
                "Blues shouter",
                "Bolero",
                "Bongo flava",
                "Boogaloo",
                "Boogie",
                "Boogie-woogie",
                "Boom bap",
                "Bossa Nova",
                "Bouncy techno",
                "Bouyon",
                "Brazilian",
                "Brazilian bass",
                "Brazilian rock",
                "Breakbeat",
                "Breakbeat hardcore",
                "Breakcore",
                "Breakstep",
                "Brega",
                "Brill building",
                "British blues",
                "British dance band",
                "British folk revival",
                "British hip hop",
                "Britpop",
                "Broken beat",
                "Brostep",
                "Bubblegum pop",
                "Bullerengue",
                "Cadence-lypso",
                "Cajun",
                "Cajun fiddle tunes",
                "Calypso",
                "Canadian blues",
                "Canción",
                "Canterbury scene",
                "Cantopop",
                "Canzone",
                "Cape jazz",
                "Caribbean and Caribbean-influenced",
                "Carnatic",
                "Celtic",
                "Celtic metal",
                "Celtic punk",
                "Celtic rock",
                "Cha-cha-chá",
                "Chalga",
                "Chamber jazz",
                "Changa tuki",
                "Chanson",
                "Chap hop",
                "Chicago blues",
                "Chicago hard house",
                "Chicago house",
                "Chicha",
                "Chill-out",
                "Chillwave",
                "Chimurenga",
                "Chiptune",
                "Chopper rap",
                "Choro",
                "Christian country",
                "Christian hip hop",
                "Christian metal",
                "Christian pop",
                "Christian punk",
                "Christian rock",
                "Chutney",
                "Chutney parang",
                "Chutney soca",
                "City pop",
                "Classic alternative",
                "Classic country",
                "Classic female blues",
                "Classic Hip Hop",
                "Classic hits",
                "Classic Rock",
                "Classical",
                "Classical crossover",
                "Classical period",
                "Close harmony",
                "Cloud rap",
                "Cold wave",
                "Compas",
                "Complextro",
                "Congolese rumba",
                "Conscious hip hop",
                "Contemporary classical",
                "Contemporary folk",
                "Contemporary R&B",
                "Continental jazz",
                "Cool jazz",
                "Corrido",
                "Country",
                "Country blues",
                "Country pop",
                "Country rap",
                "Country rock",
                "Coupé-Décalé",
                "Cowboy/Western",
                "Cowpunk",
                "C-pop",
                "Cringe pop",
                "Criolla",
                "Crossover jazz",
                "Crossover thrash",
                "Crunk",
                "Crunkcore",
                "Crust punk",
                "Crustgrind",
                "Cumbia",
                "Cybergrind",
                "Dancehall",
                "Dancehall pop",
                "Dance-pop",
                "Dance-punk",
                "Dance-rock",
                "Dangdut",
                "Danger",
                "Dansband",
                "Dark ambient",
                "Dark cabaret",
                "Dark electro",
                "Dark psytrance",
                "Dark wave",
                "Darkcore",
                "Darkstep",
                "D-beat",
                "Death industrial",
                "Death metal",
                "Death 'n' roll",
                "Deathcore",
                "Death-doom",
                "Deathgrind",
                "Deathrock",
                "Deconstructed club",
                "Deep funk",
                "Deep house",
                "Delta blues",
                "Desert rock",
                "Detroit blues",
                "Detroit techno",
                "Digital hardcore",
                "Dirty rap",
                "Disco",
                "Disco polo",
                "Diva house",
                "Dixieland",
                "Djent",
                "Dohori",
                "Doom metal",
                "Doomcore",
                "Doo-wop",
                "Downtempo",
                "Dream pop",
                "Dream trance",
                "Drill",
                "Drill 'n' bass",
                "Drone",
                "Drone metal",
                "Drum and bass",
                "Drumstep",
                "Dub",
                "Dub poetry",
                "Dub techno",
                "Dubstep",
                "Dubstyle",
                "Dubtronica",
                "Dunedin sound",
                "Dungeon synth",
                "Dutch house",
                "Early",
                "East Asian",
                "Easy listening",
                "Electric blues",
                "Electro",
                "Electro house",
                "Electro swing",
                "Electroacoustic",
                "Electroacoustic improvisation",
                "Electroclash",
                "Electro-disco",
                "Electro-industrial",
                "Electronic",
                "Electronic body",
                "Electronic rock",
                "Electronica",
                "Electronicore",
                "Electropop",
                "Elevator",
                "Emo",
                "Emo pop",
                "Emo rap",
                "Enka",
                "Ethereal wave",
                "Ethnic electronica",
                "Ethno jazz",
                "Euro disco",
                "Euro house",
                "Eurobeat",
                "Eurodance",
                "European free jazz",
                "Europop",
                "Euro-trance",
                "Experimental",
                "Experimental hip hop",
                "Experimental rock",
                "Extratone",
                "Fado",
                "Fann at-Tanbura",
                "Fidget house",
                "Fijiri",
                "Filk",
                "Filmi",
                "Flamenco",
                "Florida breaks",
                "FM synthesis",
                "Folk",
                "Folk metal",
                "Folk pop",
                "Folk punk",
                "Folk rock",
                "Folktronica",
                "Footwork",
                "Forró",
                "Freak folk",
                "Freakbeat",
                "Free funk",
                "Free improvisation",
                "Free jazz",
                "Free tekno",
                "Freestyle",
                "French house",
                "French pop",
                "Frenchcore",
                "Frevo",
                "Fuji",
                "Full-On",
                "Funk",
                "Funk carioca",
                "Funk Metal",
                "Funk ostentação",
                "Funk rock",
                "Funkstep",
                "Funktronica",
                "Funky house",
                "Furniture",
                "Future bass",
                "Future funk",
                "Future garage",
                "Future house",
                "Futurepop",
                "Gabber",
                "galant",
                "Gamelan",
                "Gangsta rap",
                "Garage house",
                "Garage punk",
                "Garage rock",
                "Genge",
                "G-funk",
                "Ghetto house",
                "Ghettotech",
                "Glam metal",
                "Glam rock",
                "Glitch",
                "Glitch hop",
                "Goa trance",
                "Go-go",
                "Golden age hip hop",
                "Goregrind",
                "Gospel",
                "Gospel blues",
                "Gothic metal",
                "Gothic rock",
                "Gqom",
                "Grime",
                "Grindcore",
                "Grindie",
                "Groove metal",
                "Grunge",
                "Grupera",
                "Guajira",
                "Gypsy jazz",
                "Gypsy punk",
                "Hands up",
                "Happy hardcore",
                "Hard bop",
                "Hard dance",
                "Hard NRG",
                "Hard rock",
                "Hard trance",
                "Hardbag",
                "Hardbass",
                "Hardcore",
                "Hardcore hip hop",
                "Hardcore punk",
                "Hardstep",
                "Hardstyle",
                "Hardtechno",
                "Hardvapour",
                "Harsh noise",
                "Harsh noise wall",
                "Hauntology",
                "Heavy metal",
                "Hellbilly",
                "high modernism",
                "Highlife",
                "Hill country blues",
                "Hindustani",
                "Hi-NRG",
                "Hip hop",
                "Hip hop soul",
                "Hip hop fusion genres",
                "Hip house",
                "Hip pop",
                "Hiplife",
                "Hipster hop",
                "Hokkien pop",
                "Hokum",
                "Hokum blues",
                "Hong Kong English pop",
                "Honky-tonk",
                "Horror punk",
                "Horrorcore",
                "House",
                "Huayno",
                "Hyperpop",
                "Hyphy",
                "Hypnagogic pop",
                "Igbo highlife",
                "Igbo rap",
                "Illbient",
                "Impressionism",
                "Indian pop",
                "Indie folk",
                "Indie pop",
                "Indie rock",
                "Indietronica",
                "Industrial folk",
                "Industrial hip hop",
                "Industrial metal",
                "Industrial rock",
                "Industrial techno",
                "Industrial \\ post-industrial",
                "Instrumental country",
                "Instrumental hip hop",
                "Intelligent dance",
                "Intelligent drum and bass",
                "Iranian pop",
                "Isicathamiya",
                "Isolationism",
                "Italo dance",
                "Italo disco",
                "Italo house",
                "Jangle pop",
                "Japanoise",
                "Jazz",
                "Jazz blues",
                "Jazz fusion",
                "Jazz house",
                "Jazz rap",
                "Jazz rock",
                "Jazz-funk",
                "Jazzstep",
                "Jazztronica",
                "Jerkin'",
                "Jersey club",
                "Jit",
                "J-pop",
                "Jùjú",
                "Juke house",
                "Jump blues",
                "Jumpstyle",
                "Jump-up",
                "Jungle",
                "Jungle terror",
                "Kadongo Kamu",
                "Kansas City blues",
                "Kansas City jazz",
                "Kapuka",
                "Kawaii future bass",
                "Kawaii metal",
                "Kayōkyoku",
                "Keroncong",
                "Khaliji",
                "Kidandali",
                "Kizomba",
                "Korean hip hop",
                "Korean rock",
                "K-pop",
                "Krautrock",
                "Kuduro",
                "Kwaito",
                "Kwassa kwassa",
                "Kwela",
                "Laïkó",
                "Lambada",
                "Laptronica",
                "Latin",
                "Latin alternative",
                "Latin ballad",
                "Latin Christian",
                "Latin freestyle",
                "Latin house",
                "Latin jazz",
                "Latin metal",
                "Latin pop",
                "Latin rock",
                "Latin trap",
                "Lavani",
                "Lento violento",
                "Liquid funk",
                "Live electronics",
                "Livetronica",
                "Liwa",
                "Lo-fi hip hop",
                "Louisiana blues",
                "Louisiana swamp pop",
                "Lounge",
                "Lovers rock",
                "Low Bap",
                "Lowercase",
                "Luk Krung",
                "Luk Thung",
                "Lyrical hip hop",
                "Madchester",
                "Mahraganat",
                "Mainstream hardcore",
                "Mainstream jazz",
                "Mákina",
                "Makossa",
                "Mallsoft",
                "Maloya",
                "Mambo",
                "Mandopop",
                "Manila sound",
                "Maracatu",
                "Mariachi",
                "Martial industrial",
                "Math rock",
                "Mathcore",
                "Mbalax",
                "Mbaqanga",
                "M-Base",
                "Mbube",
                "Medieval",
                "Medieval metal",
                "Melbourne bounce",
                "Melodic Black Metal",
                "Melodic death metal",
                "Melodic funk",
                "Melodic hardcore",
                "Melodic metalcore",
                "Memphis blues",
                "Mento",
                "Merengue",
                "Merenhouse",
                "Merenrap",
                "Méringue",
                "Metalcore",
                "Metalstep",
                "Mexican pop",
                "Mexican son",
                "Miami bass",
                "Microhouse",
                "Middle of the road",
                "Minimal techno",
                "Minimal wave",
                "Minneapolis Sound",
                "Modal jazz",
                "Modernism",
                "Moombahcore",
                "Moombahton",
                "Morlam",
                "Morna",
                "Motswako",
                "Mozambique",
                "Mumble rap",
                "Música criolla",
                "Música popular brasileira",
                "Música sertaneja",
                "Musique concrète",
                "Nagoya kei",
                "Nashville sound",
                "National Socialist Black Metal",
                "Nazi punk",
                "Ndombolo",
                "Nederpop",
                "Neo soul",
                "Neo-bop jazz",
                "Neoclassical dark wave",
                "Neoclassical metal",
                "Neoclassical new-age",
                "Neoclassicism",
                "Neofolk",
                "Neon pop",
                "Neo-progressive rock",
                "Neo-psychedelia",
                "Neo-swing",
                "Neotraditional country",
                "Nerdcore",
                "Neue Deutsche Härte",
                "Neue Deutsche Todeskunst",
                "Neue Deutsche Welle",
                "Neurofunk",
                "New beat",
                "New jack swing",
                "New Jersey sound",
                "New Mexico",
                "New prog",
                "New rave",
                "New romantic",
                "New school hip hop",
                "New wave",
                "New-age",
                "Nintendocore",
                "Nitzhonot",
                "No wave",
                "Noise",
                "Noise rock",
                "Noisegrind",
                "Nortec",
                "Norteño",
                "Northern soul",
                "Novelty ragtime",
                "Nu jazz",
                "Nu Metal",
                "Nu skool breaks",
                "Nu-disco",
                "Nueva canción",
                "Nu-gaze",
                "Oi!",
                "Old school hip hop",
                "Oldies",
                "Onkyokei",
                "Operatic pop",
                "OPM",
                "Orchestral jazz",
                "Original Pilipino",
                "Outlaw country",
                "Outsider house",
                "Pagan metal",
                "Pagode",
                "Paisley Underground",
                "Palm-wine",
                "PBR&B",
                "P-Funk",
                "Phonk",
                "Pichakaree",
                "Piedmont blues",
                "Pinoy pop",
                "Plunderphonics",
                "Political hip hop",
                "Pop",
                "Pop punk",
                "Pop rap",
                "Pop rock",
                "Pop soul",
                "Pop sunda",
                "Porro",
                "Post-bop",
                "Post-disco",
                "Post-dubstep",
                "Post-grunge",
                "Post-hardcore",
                "Post-metal",
                "postmodern",
                "Post-punk",
                "Post-punk revival",
                "Post-rock",
                "Power electronics",
                "Power metal",
                "Power noise",
                "Power pop",
                "Powerviolence",
                "Powwow-step",
                "Progressive bluegrass",
                "Progressive breaks",
                "Progressive country",
                "Progressive electronic",
                "Progressive folk",
                "Progressive house",
                "Progressive metal",
                "Progressive pop",
                "Progressive psytrance",
                "Progressive rock",
                "Progressive trance",
                "Proibidão",
                "Protest song",
                "Psybient",
                "Psychedelic folk",
                "Psychedelic pop",
                "Psychedelic rock",
                "Psychedelic trance",
                "Psychobilly",
                "Psychobilly/Punkabilly",
                "Psydub",
                "Pumping house",
                "Punk blues",
                "Punk jazz",
                "Punk pathetique",
                "Punk rock",
                "Punta",
                "Punta rock",
                "R&B and soul",
                "Rabòday",
                "Raga rock",
                "Ragga",
                "Ragga jungle",
                "Raggacore",
                "Ragini",
                "Ragtime",
                "Raï",
                "Ranchera",
                "Rap Metal",
                "Rap rock",
                "Rapcore",
                "Rara tech",
                "Rasin",
                "Rasteirinha",
                "Reactionary bluegrass",
                "Rebetiko",
                "Red dirt",
                "Reductionism",
                "Reggae",
                "Reggae fusion",
                "Reggae rock",
                "Reggaestep",
                "Reggaeton",
                "Regional Mexican",
                "Renaissance",
                "Rhythm and blues",
                "Riddim",
                "Riot grrrl",
                "Rock",
                "Rock and roll",
                "Rock en Español",
                "Rock in Opposition",
                "Rockabilly",
                "Rocksteady",
                "Romantic",
                "Roots reggae",
                "Rumba",
                "Russian pop",
                "Sadcore",
                "Sakara",
                "Salsa",
                "Salsa romántica",
                "Samba",
                "Samba rock",
                "Sambass",
                "Sampledelia",
                "Sawt",
                "Schaffel",
                "Schlager",
                "Scouse house",
                "Screamo",
                "Sega",
                "Seggae",
                "Semba",
                "Sequencer",
                "Sertanejo",
                "Shamstep",
                "Shangaan electro",
                "Shibuya-kei",
                "Shoegaze",
                "Singer-songwriter",
                "Ska",
                "Ska jazz",
                "Ska punk",
                "Skate punk",
                "Skiffle",
                "Skweee",
                "Slime punk",
                "Slowcore",
                "Sludge metal",
                "Smooth jazz",
                "Snap",
                "Soca",
                "Soft rock",
                "Son",
                "Son cubano",
                "Songo",
                "Sophisti-pop",
                "Soukous",
                "Soul",
                "Soul blues",
                "Soul jazz",
                "South and southeast Asian",
                "Southern rock",
                "Southern soul",
                "Sovietwave",
                "Space",
                "Space age pop",
                "Space disco",
                "Space rock",
                "Spacesynth",
                "Speed garage",
                "Speed metal",
                "Speedcore",
                "Splittercore",
                "St. Louis blues",
                "Stoner rock",
                "Straight-ahead jazz",
                "Street punk",
                "Stride jazz",
                "Sufi rock",
                "Sung poetry",
                "Sunshine pop",
                "Sunshine reggae",
                "Suomisaundi",
                "Surf pop",
                "Surf rock",
                "Swamp blues",
                "Swing",
                "Symphonic black metal",
                "Symphonic metal",
                "Synthpop",
                "Synth-pop",
                "Synth-punk",
                "Synthwave",
                "Taarab",
                "Taiwanese pop",
                "Tango",
                "Tech house",
                "Tech trance",
                "Technical death metal",
                "Techno",
                "Techstep",
                "Tecnobrega",
                "Teen pop",
                "Tejano",
                "Texas blues",
                "Texas country",
                "Thai pop",
                "Third stream",
                "Thrash metal",
                "Thrashcore",
                "Timba",
                "T'ong guitar",
                "Toytown techno",
                "Trad jazz",
                "Traditional",
                "Traditional country",
                "Traditional pop",
                "Trance",
                "Trap",
                "Tribal house",
                "Trip hop",
                "Trival",
                "Tropical",
                "Tropical house",
                "Tropicalia",
                "Tropipop",
                "Trot",
                "Truck-driving country",
                "Turkish pop",
                "Twee pop",
                "Twoubadou",
                "UK bass",
                "UK drill",
                "UK funky",
                "UK garage",
                "UK hard house",
                "UK trap",
                "Unblack metal",
                "Uplifting trance",
                "Urban Pasifika",
                "Vallenato",
                "Vaporwave",
                "Video game",
                "Viking metal",
                "Vispop",
                "Visual kei",
                "Vocal jazz",
                "Vocal trance",
                "Vocaloid",
                "V-pop",
                "War metal",
                "West Coast blues",
                "West Coast hip hop",
                "West Coast jazz",
                "Western",
                "Western swing",
                "Witch house",
                "Wonky",
                "Wonky pop",
                "World fusion",
                "Worldbeat",
                "Zenonesque",
                "Zouglou",
                "Zouk",
"Zouk-Lambada",
"Zydeco" };

            return PickRandom(genres);
        }

    }
}
