name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file ./SpotifyStalker2/Dockerfile --tag spotifystalker2:$(date +%s)
        docker push ghcr.io/osbornesupremacy/spotifystalker2:latest
