name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.ioW
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build . --file ./SpotifyStalker2/Dockerfile --tag ghcr.io/osbornesupremacy/spotifystalker2:latest
        docker push ghcr.io/osbornesupremacy/spotifystalker2:latest

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'spotifystalker'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'https://ghcr.io/osbornesupremacy/spotifystalker2:latest'
