name: Check out code
use: actions/checkout@v2

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./SpotifyStalker2 --file Dockerfile --tag spotifystalker:$(date +%s)
